[project]
name = "dspy_local"
version = "0.1.0"
description = "Local Dspy projects"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.6.2",
    "dspy>=2.6.27",
    "rich>=14.0.0",
]
